apiVersion: v1
kind: ConfigMap
metadata:
  name: ironfish-node-offline-config
  namespace: kube-system
data:
  service-conf: |
      {
          "enableListenP2P":false,
          "enableSyncing":false,
          "enableRpcTcp":true,
          "enableRpcTls":false,
          "rpcTcpHost":"0.0.0.0",
          "rpcTcpPort":50750
      }


